version: "3.8"

services:
  # fastapi
  app:
    build:
      context: .
    restart: unless-stopped
    container_name: fastapi
    ports:
      - 8000:8000
    environment:
      - ENABLE_METRICS=true
      - METRICS_NAMESPACE=fastapi
      - METRICS_SUBSYSTEM=model
  # prometheus
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  # grafana
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
