apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python # this must match the labels we set on the pod
  ports:
    - protocol: "TCP" # the network protocol to use with the port
      port: 6000 # port that incoming traffic goes to
      targetPort: 5000 # port on the pod that traffic should be sent to
  type: LoadBalancer # type with which service is exposed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-api
spec:
  selector:
    matchLabels:
      app: hello-python # this must match the labels we set on the pod
  replicas: 4 # tells deployment number of identical pods to create
  template:
    metadata:
      labels:
        app: hello-python # labels on the pod
    spec:
      containers:
        - name: hello-python-container
          image: digitalocean/flask-helloworld:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
