apiVersion: v1
kind: Pod
metadata:
  name: python3-pod
  labels:
    app: python3
spec:
  containers:
    - name: python3-container
      image: python:3.8
      command: ["python3", "-c", 'print("Hello, World!")']
      resources:
        requests:
          memory: 0.5Gi
          cpu: "0.25"
        limits:
          memory: 1Gi
          cpu: "0.5"
      restartPolicy: Never
