apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-model
  labels:
    app: sentiment-model
spec:
  selector:
    matchLabels:
      app: sentiment-model
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sentiment-model
    spec:
      containers:
        - name: fastapi-sentiment-model
          image: ghcr.io/dudeperf3ct/sentiment-fastapi:main
          imagePullPolicy: Always
          env:
            - name: ENABLE_METRICS
              value: "true"
            - name: METRICS_NAMESPACE
              value: "fastapi"
            - name: METRICS_SUBSYSTEM
              value: "model"
          ports:
            - name: app
              containerPort: 8000
          resources:
            requests:
              memory: 0.5Gi
              cpu: "0.25"
            limits:
              memory: 1Gi
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-model-service
  labels:
    app: sentiment-model
spec:
  selector:
    app: sentiment-model
  ports:
    - name: app
      port: 8000
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-model-servicemonitor
  # must be the same namespace that Prometheus is running in
  namespace: monitoring
  labels:
    app: sentiment-model
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: sentiment-model
  endpoints:
    - path: metrics
      port: app
      interval: 15s
  namespaceSelector:
    any: true
